IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Skills')
CREATE TABLE Skills (
Id INT IDENTITY NOT NULL PRIMARY KEY,
Name NVARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO Skills (Name)
VALUES
('.Net MVC'),
('VueJS'),
('C#'),
('CSS'),
('HTML');