IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Departments')
CREATE TABLE Departments (
Id INT IDENTITY NOT NULL PRIMARY KEY,
Name NVARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO Departments (Name)
VALUES
('Management'),
('Financial'),
('Development');